FROM python:3.9-slim
WORKDIR /app
RUN pip install streamlit pandas plotly s3fs minio
COPY dashboard.py .
EXPOSE 8501
CMD ["streamlit", "run", "dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]